# This workflow build's docker image and push that image to GCP
#

name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  composer:
    runs-on: [self-hosted, dind]

    steps:
      - uses: actions/checkout@v3
        with:
          clean: true

      - name: Set SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.COMPOSER_SSH }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          command: install
          version: 1
          only_args: --no-interaction --no-suggest
          php_version: 7.2
          php_extensions: json pcov
          ssh_key: ${{ secrets.COMPOSER_SSH }}

      - name: Create phpunit.xml
        run: mv phpunit.xml.dist phpunit.xml

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          version: 8.5.2
          php_version: 7.2
          php_extensions: json pcov
          configuration: phpunit.xml
          memory_limit: "1G"
          coverage_clover: coverage.xml
